import { Helmet } from 'react-helmet-async';

export const Disclaimer = () => (
  <div className="max-w-4xl mx-auto px-6 py-16 text-slate-300">
    <Helmet>
      <title>Disclaimer | Logbook Wrapped</title>
      <meta name="description" content="Legal and liability disclaimer for the Logbook Wrapped platform." />
    </Helmet>
    <h1 className="text-4xl font-bold text-white mb-6">Disclaimer</h1>
    <div className="space-y-6 leading-relaxed">
      <p>
        Logbook Wrapped is an independent tool created for entertainment and personal visualization purposes. 
      </p>
      <h2 className="text-2xl font-semibold text-white mt-8 mb-2">Not an Official Record</h2>
      <p>
        The statistics, calculations, and visuals generated by Logbook Wrapped <strong>do not constitute official aviation records</strong>. Pilots must rely on their official physical logbooks or certified electronic logbooks for currency, insurance, and regulatory (FAA, EASA, etc.) compliance. 
      </p>
      <h2 className="text-2xl font-semibold text-white mt-8 mb-2">No Affiliation</h2>
      <p>
        Logbook Wrapped is not affiliated with, endorsed by, or sponsored by ForeFlight, Garmin Pilot, MyFlightbook, Spotify, or any other trademarked entities mentioned on this site.
      </p>
      <h2 className="text-2xl font-semibold text-white mt-8 mb-2">Accuracy</h2>
      <p>
        While our CSV normalizer strives for high accuracy, errors in parsing may occur due to non-standard user inputs or updates to EFB export formats. We assume no liability for inaccuracies.
      </p>
    </div>
  </div>
);