import { Helmet } from 'react-helmet-async';
import { AlertTriangle, Mail, Scale, FileText } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

export const Disclaimer = () => {

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }} 
      animate={{ opacity: 1, y: 0 }} 
      className="max-w-4xl mx-auto px-6 py-16 text-slate-300"
    >
      <Helmet>
        <title>Disclaimer | LogbookWrapped</title>
        <meta name="description" content="Legal and liability disclaimer for the Logbook Wrapped platform." />
      </Helmet>

      <header className="mb-12">
        <h1 className="text-4xl font-bold text-white mb-6">Disclaimer</h1>
        <p className="text-xl leading-relaxed">
          Logbook Wrapped is an independent tool created for entertainment and personal visualization. 
          By using this service, you acknowledge the following terms.
        </p>
      </header>

      <div className="space-y-10">
        {/* Regulatory Warning */}
        <section className="bg-orange-500/10 border border-orange-500/20 p-8 rounded-2xl flex gap-6 items-start">
          <div className="hidden sm:block mt-1">
            <AlertTriangle className="text-orange-500" size={32} />
          </div>
          <div>
            <h2 className="text-2xl font-semibold text-white mb-2">Not an Official Record</h2>
            <p className="text-lg leading-relaxed">
              The statistics and visuals generated by Logbook Wrapped <strong>do not constitute official aviation records</strong>. 
              Pilots must rely on their official physical or certified electronic logbooks for currency, 
              insurance, and regulatory (FAA, EASA, etc.) compliance.
            </p>
          </div>
        </section>

        <div className="grid gap-8 md:grid-cols-2">
          {/* Trademark Section */}
          <section className="bg-slate-800/40 border border-slate-700/50 p-8 rounded-2xl">
            <Scale className="text-blue-400 mb-4" size={28} />
            <h2 className="text-xl font-semibold text-white mb-3">No Affiliation</h2>
            <p className="leading-relaxed text-slate-400">
              Logbook Wrapped is not affiliated with, endorsed by, or sponsored by 
              <span className="text-slate-200"> ForeFlight, Garmin Pilot, MyFlightbook, Spotify</span>, 
              or any other trademarked entities mentioned on this site.
            </p>
          </section>

          {/* Accuracy Section */}
          <section className="bg-slate-800/40 border border-slate-700/50 p-8 rounded-2xl">
            <FileText className="text-emerald-400 mb-4" size={28} />
            <h2 className="text-xl font-semibold text-white mb-3">Data Accuracy</h2>
            <p className="leading-relaxed text-slate-400">
              While our normalizer strives for high accuracy, parsing errors may occur due to 
              non-standard inputs or EFB updates. We assume no liability for inaccuracies.
            </p>
          </section>
        </div>

        {/* Contact Link Section */}
        <section className="mt-16 py-12 border-t border-slate-800 text-center">
          <p className="mb-6 text-slate-400">
            Notice a calculation error or an unsupported logbook format?
          </p>
          <Link 
            to="/contact"
            className="inline-flex items-center gap-3 px-8 py-4 bg-white text-slate-900 font-bold rounded-full transition-all hover:scale-105 active:scale-95 hover:bg-slate-100 shadow-xl shadow-white/10"
          >
            <Mail size={20} />
            Contact Us to Report an Issue
          </Link>
        </section>
      </div>
    </motion.div>
  );
};